import type {
  Activity,
  AuditEntry,
  CalendarEvent,
  Channel,
  ChatMessage,
  Document,
  Milestone,
  Notification,
  Person,
  Project,
  Report,
  ReportStatus,
  Task,
} from "./types";

export const PEOPLE: Person[] = [
  {
    id: "sekhar",
    name: "K. Hari Chandra Sekhar",
    short: "CS",
    role: "super_admin",
    title: "Admin Lead · Faculty PM",
    dept: "CSE Faculty",
    email: "hcskolluru@gmail.com",
    presence: "active",
    phone: "+91 94401 23456",
    college: "RV Institute of Technology",
    location: "Bengaluru, India",
    bio: "Super Administrator & Faculty PM overseeing technical operations, engineering capstones, and institutional research.",
    linkedin_url: "https://linkedin.com/in/hcsekhar",
    projectIds: ["team-portal", "capstone-ops"],
    hoursThisWeek: 24,
    taskLoad: 3,
    streak: 48,
    attendance: 100,
  },
  {
    id: "shaik",
    name: "Muhammad Ayyoob Shaik",
    short: "AS",
    role: "faculty",
    title: "Faculty Guide · Project Advisor",
    dept: "ECE Faculty",
    email: "shaikmuhammadayyoob@gmail.com",
    presence: "active",
    phone: "+91 98850 12345",
    college: "RV Institute of Technology",
    location: "Bengaluru, India",
    bio: "Faculty Guide mentoring hardware-software co-design, embedded firmware, and IoT telemetry architectures.",
    linkedin_url: "https://linkedin.com/in/ayyoob-shaik",
    projectIds: ["team-portal", "capstone-ops"],
    hoursThisWeek: 16,
    taskLoad: 2,
    streak: 35,
    attendance: 100,
  },
  {
    id: "vardan",
    name: "Malla Sai Vardan",
    short: "SV",
    role: "lead",
    title: "Technical Lead · Full-Stack & Cloud",
    dept: "CSE, Year 4",
    year: "Year 4",
    reg: "RVIT-CS-2022-001",
    email: "mallasaivardan@gmail.com",
    presence: "active",
    phone: "+91 97000 12345",
    college: "RV Institute of Technology",
    location: "Bengaluru, India",
    bio: "Team Lead driving distributed systems, full-stack microservices, and student engineering deliverables.",
    skills: "TypeScript, React, PostgreSQL, Docker, Node.js",
    linkedin_url: "https://linkedin.com/in/saivardan",
    github_url: "https://github.com/saivardan",
    projectIds: ["team-portal", "capstone-ops"],
    hoursThisWeek: 35,
    taskLoad: 5,
    streak: 26,
    attendance: 98.9,
  },
  {
    id: "raviteja",
    name: "Javvadi Raviteja",
    short: "JR",
    role: "member",
    title: "Engineering Intern · Frontend & Systems",
    dept: "CSE, Year 3",
    year: "Year 3",
    reg: "RVIT-CS-2023-014",
    email: "jraviteja2007@gmail.com",
    presence: "active",
    phone: "+91 91234 56789",
    college: "RV Institute of Technology",
    location: "Bengaluru, India",
    bio: "Frontend engineer working on UI components, reactive state management, and real-time dashboards.",
    skills: "React, Tailwind CSS, TypeScript, Next.js",
    linkedin_url: "https://linkedin.com/in/jraviteja",
    projectIds: ["team-portal", "capstone-ops"],
    hoursThisWeek: 22,
    taskLoad: 4,
    streak: 19,
    attendance: 97.4,
  },
  {
    id: "hemasree",
    name: "K. Hemasree",
    short: "KH",
    role: "member",
    title: "Engineering Intern · ML & Data",
    dept: "CSE, Year 3",
    year: "Year 3",
    reg: "RVIT-CS-2023-028",
    email: "hemaprasad3598@gmail.com",
    presence: "active",
    phone: "+91 93456 78901",
    college: "RV Institute of Technology",
    location: "Bengaluru, India",
    bio: "Machine learning enthusiast researching neural vision models and automated sensor data analysis.",
    skills: "Python, PyTorch, OpenCV, Data Analysis",
    linkedin_url: "https://linkedin.com/in/hemasree-k",
    projectIds: ["team-portal", "capstone-ops"],
    hoursThisWeek: 21,
    taskLoad: 3,
    streak: 17,
    attendance: 98.1,
  },
  {
    id: "naresh",
    name: "Naresh Pagadala",
    short: "NP",
    role: "member",
    title: "Engineering Intern · Embedded Systems",
    dept: "ECE, Year 3",
    year: "Year 3",
    reg: "RVIT-EC-2023-042",
    email: "pagadalanaresh40@gmail.com",
    presence: "active",
    phone: "+91 95678 90123",
    college: "RV Institute of Technology",
    location: "Bengaluru, India",
    bio: "Embedded developer focusing on microcontroller programming, RTOS, and sensor fusion.",
    skills: "C, C++, ESP32, FreeRTOS, MQTT",
    linkedin_url: "https://linkedin.com/in/naresh-pagadala",
    projectIds: ["team-portal", "capstone-ops"],
    hoursThisWeek: 24,
    taskLoad: 4,
    streak: 14,
    attendance: 96.5,
  },
];

export const PROJECTS: Project[] = [
  {
    id: "team-portal",
    code: "PROJ-001",
    name: "RVIT TeamHub Operations Portal",
    subtitle: "React 19 / TanStack / PostgreSQL · RBAC System",
    status: "healthy",
    progress: 88,
    leadId: "vardan",
    facultyId: "shaik",
    memberIds: ["vardan", "raviteja", "hemasree", "naresh"],
    targetDate: "20 Sep",
    targetNote: "Milestone Gold",
    cycle: "Sprint 01",
    repo: "rvit-tech/team-portal",
    preview: "http://localhost:8080",
    abstract:
      "Institutional project execution system centralizing capstone artifacts, sprint reviews, TRD validation, and faculty supervisor oversight for engineering cohorts.",
    stack: [
      { name: "React 19", note: "Frontend" },
      { name: "TypeScript", note: "Strict" },
      { name: "PostgreSQL", note: "v16" },
      { name: "Tailwind", note: "v4" },
      { name: "Supabase", note: "Storage" },
    ],
  },
  {
    id: "capstone-ops",
    code: "PROJ-002",
    name: "Institutional Engineering Capstone",
    subtitle: "Research & Systems Innovation Platform",
    status: "healthy",
    progress: 72,
    leadId: "vardan",
    facultyId: "shaik",
    memberIds: ["vardan", "raviteja", "hemasree", "naresh"],
    targetDate: "30 Sep",
    targetNote: "Midterm Review",
    cycle: "Sprint 01",
    repo: "rvit-tech/capstone-ops",
    preview: "http://localhost:8080/projects/capstone-ops",
    abstract:
      "Collaborative engineering and interdisciplinary research platform supervised by department faculty advisors.",
    stack: [
      { name: "Python", note: "3.12" },
      { name: "FastAPI", note: "Workers" },
      { name: "Docker", note: "Containerized" },
    ],
  },
];

export const TASKS: Task[] = [
  {
    id: "t-101",
    code: "RVIT-101",
    title: "Implement RBAC Permission Middleware & Session Storage",
    projectId: "team-portal",
    assigneeId: "raviteja",
    assignerId: "vardan",
    priority: "high",
    status: "in_progress",
    progress: 80,
    due: "2026-09-15",
    dueLabel: "In 3 days",
    branch: "feat/rbac-middleware",
    subtasks: [
      { id: "s1", title: "Define database schema & role hierarchy enum", done: true },
      { id: "s2", title: "Session verification middleware with token rotation", done: true },
      { id: "s3", title: "Audit logging on permission check", done: false },
    ],
  },
  {
    id: "t-102",
    code: "RVIT-102",
    title: "Unit & Security Tests for Auth Controller & RBAC Gates",
    projectId: "team-portal",
    assigneeId: "raviteja",
    assignerId: "vardan",
    priority: "medium",
    status: "in_progress",
    progress: 60,
    due: "2026-09-16",
    dueLabel: "In 4 days",
    branch: "feat/auth-unit-tests",
    subtasks: [
      { id: "s1", title: "Login happy-path tests", done: true },
      { id: "s2", title: "Role-guarded endpoint test suite", done: true },
      { id: "s3", title: "Coverage gate verification", done: false },
    ],
  },
  {
    id: "t-103",
    code: "RVIT-103",
    title: "Deploy Supabase Storage Bucket for Documents & Specs",
    projectId: "team-portal",
    assigneeId: "hemasree",
    assignerId: "sekhar",
    priority: "high",
    status: "done",
    progress: 100,
    due: "2026-09-12",
    dueLabel: "Completed",
    branch: "feat/supabase-storage",
    subtasks: [
      { id: "s1", title: "Create documents bucket in Supabase", done: true },
      { id: "s2", title: "Configure signed URL generator", done: true },
      { id: "s3", title: "Verify upload and download URLs", done: true },
    ],
  },
  {
    id: "t-104",
    code: "RVIT-104",
    title: "Edge Telemetry & Hardware Sensor Ingestion Service",
    projectId: "capstone-ops",
    assigneeId: "naresh",
    assignerId: "shaik",
    priority: "high",
    status: "in_progress",
    progress: 65,
    due: "2026-09-18",
    dueLabel: "In 6 days",
    branch: "feat/sensor-telemetry",
    subtasks: [
      { id: "s1", title: "ESP32 firmware serial comms", done: true },
      { id: "s2", title: "MQTT topic subscription handler", done: true },
      { id: "s3", title: "Buffering and SQLite/Postgres persistence", done: false },
    ],
  },
];

export const REPORTS: Report[] = [
  {
    id: "r-ravi-01",
    authorId: "raviteja",
    projectId: "team-portal",
    date: "2026-09-11",
    hours: 6.5,
    completed:
      "• Completed auth-first route guards in AppShell.\n• Purged mock persona switchers from settings and sidebar.\n• Verified chat persistent message publishing to PostgreSQL.",
    next: "• Finalize document center signed uploads.\n• Write additional automated tests.",
    blockers: "",
    progress: 80,
    status: "submitted",
    prUrl: "https://github.com/rvit-tech/team-portal/pull/42",
    taskCodes: ["RVIT-101"],
    submittedAt: "17:42 IST",
  },
  {
    id: "r-hema-01",
    authorId: "hemasree",
    projectId: "team-portal",
    date: "2026-09-11",
    hours: 6.0,
    completed:
      "• Configured Supabase Storage bucket documents.\n• Verified profile image upload with presigned URLs.",
    next: "• Connect ML document tagging pipeline.",
    blockers: "",
    progress: 75,
    status: "approved",
    taskCodes: ["RVIT-103"],
    submittedAt: "16:30 IST",
    feedback: "Storage integration verified on staging.",
  },
  {
    id: "r-naresh-01",
    authorId: "naresh",
    projectId: "capstone-ops",
    date: "2026-09-11",
    hours: 7.0,
    completed:
      "• Configured MQTT broker connection on ESP32 node.\n• Streamed sensor telemetry packets to backend listener.",
    next: "• Implement message deduplication and error recovery.",
    blockers: "",
    progress: 65,
    status: "approved",
    taskCodes: ["RVIT-104"],
    submittedAt: "17:15 IST",
    feedback: "Hardware logs confirmed.",
  },
];

export const DOCUMENTS: Document[] = [
  {
    id: "doc-tp-prd",
    projectId: "team-portal",
    name: "TeamHub_Platform_PRD_v1.0.pdf",
    kind: "prd",
    version: "v1.0",
    updatedBy: "vardan",
    updatedAt: "Today",
    size: "1.4 MB",
    current: true,
  },
  {
    id: "doc-tp-trd",
    projectId: "team-portal",
    name: "RBAC_Architecture_TRD_v2.0.pdf",
    kind: "trd",
    version: "v2.0",
    updatedBy: "sekhar",
    updatedAt: "Yesterday",
    size: "820 KB",
    current: true,
  },
  {
    id: "doc-cap-spec",
    projectId: "capstone-ops",
    name: "Capstone_Research_Guidelines.pdf",
    kind: "spec",
    version: "v1.0",
    updatedBy: "shaik",
    updatedAt: "2 days ago",
    size: "650 KB",
    current: true,
  },
];

export const MILESTONES: Milestone[] = [
  {
    id: "m1",
    projectId: "team-portal",
    title: "Milestone 1: Requirements & DB Schema Design",
    detail: "Synthesized functional departmental use-cases into 3NF PostgreSQL models.",
    status: "done",
    date: "Completed · Aug 25",
    score: "100% Score",
    meta: "Verified by Faculty Guide",
  },
  {
    id: "m2",
    projectId: "team-portal",
    title: "Milestone 2: Auth, RBAC & Core API",
    detail: "Better Auth integration, hierarchical permissions across Student, Lead, Faculty Guide, and Super Admin.",
    status: "active",
    date: "In Progress · Target Sep 18",
    meta: "Lead: Malla Sai Vardan · 85% Complete",
  },
  {
    id: "m3",
    projectId: "capstone-ops",
    title: "Milestone 1: Capstone Research Setup",
    detail: "Student cohort onboarding, project proposal sign-offs, and architecture packs.",
    status: "active",
    date: "In Progress · Target Sep 30",
    meta: "Lead: Malla Sai Vardan · Faculty: Muhammad Ayyoob Shaik",
  },
];

export const CHANNELS: Channel[] = [
  { id: "general", name: "general", topic: "Campus-wide operations & notices", unread: 0 },
  { id: "announcements", name: "announcements", topic: "Faculty PM & Super Admin notices", unread: 0 },
  { id: "team-portal", name: "team-portal", topic: "TeamHub development standup & discussions", unread: 0 },
  { id: "capstone-ops", name: "capstone-ops", topic: "Capstone engineering research & systems", unread: 0 },
];

export const MESSAGES: ChatMessage[] = [
  {
    id: "c1",
    channelId: "announcements",
    authorId: "sekhar",
    body: "Welcome to RVIT TeamHub. Semester operations and project milestone reviews are now active.",
    at: "09:00",
  },
  {
    id: "c2",
    channelId: "team-portal",
    authorId: "vardan",
    body: "RBAC middleware and real-time chat persistence are deployed. Please submit today's reports by 18:00 IST.",
    at: "09:30",
  },
  {
    id: "c3",
    channelId: "team-portal",
    authorId: "raviteja",
    body: "All route guards and profile drawers verified. Ready for testing.",
    at: "10:15",
  },
];

export const ACTIVITY: Activity[] = [
  {
    id: "a1",
    kind: "approve",
    actorId: "shaik",
    text: "approved Daily Report by Naresh P.",
    detail: "Verified telemetry ingestion pipeline commits.",
    at: "20m ago",
  },
  {
    id: "a2",
    kind: "report",
    actorId: "raviteja",
    text: "filed daily report for TeamHub Operations",
    detail: "6.5h · Auth & chat persistence",
    at: "1h ago",
  },
  {
    id: "a3",
    kind: "upload",
    actorId: "vardan",
    text: "uploaded TeamHub_Platform_PRD_v1.0.pdf",
    detail: "RVIT TeamHub · v1.0",
    at: "2h ago",
  },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    kind: "system",
    title: "Operations Cycle Active",
    body: "All engineering leads: sync sprint goals and verify report compliance.",
    at: "Today",
    href: "/workspace",
    read: true,
  },
  {
    id: "n2",
    kind: "review",
    title: "Daily Reports Submitted",
    body: "Reports from Raviteja, Hemasree, and Naresh waiting for review.",
    at: "1h ago",
    href: "/reports",
    read: false,
  },
];

export const EVENTS: CalendarEvent[] = [
  { id: "e1", title: "Daily standup", date: "2026-09-12", time: "09:30", place: "Lab 4", kind: "standup" },
  { id: "e2", title: "Report cutoff", date: "2026-09-12", time: "18:00", place: "TeamHub", kind: "deadline" },
  { id: "e3", title: "Faculty capstone review", date: "2026-09-15", time: "10:00", place: "Seminar Hall", kind: "review" },
];

export const AUDIT: AuditEntry[] = [
  { id: "u1", actorId: "sekhar", action: "System Initialized", target: "RVIT TeamHub v1.0", at: "Today 09:00", ip: "10.12.4.1" },
  { id: "u2", actorId: "vardan", action: "Updated project specs", target: "PROJ-001", at: "Today 10:30", ip: "10.12.4.15" },
];

export const WEEKLY_HOURS: Record<string, { day: string; hours: number; status: ReportStatus | "none" }[]> = {
  raviteja: [
    { day: "Mon 8", hours: 6, status: "approved" },
    { day: "Tue 9", hours: 7.5, status: "approved" },
    { day: "Wed 10", hours: 6, status: "approved" },
    { day: "Thu 11", hours: 6.5, status: "submitted" },
    { day: "Fri 12", hours: 0, status: "none" },
  ],
};

export const COMPLIANCE_TODAY = {
  received: 3,
  total: 4,
  pending: [] as string[],
};

export const TODAY = "2026-09-11";
export const TODAY_LABEL = "Thursday, Sep 11, 2026";
export const CYCLE = "OPS CYCLE Q3 · W9";
